### ISSUE TITLE
PDF export suite

### ISSUE THREAD

**Issue by snazzyDocs** [snazzyDocs/public-snazzyDocs#69]
This is a central place to outline the ideal feature-list related to the future planned PDF export suite.

- [x] Add image to cover page - #54
- [x] Add watermark logo on each page - #54
- [x] Image grouping for non page breaking - (Undecided) #67
- [ ] Better export menu UX - #44 
- [x] Hosting PDF files - #68 
- [ ] Print to PDF button in customer facing docs

**Comment by snazzyDocs** [comment]
**PDF hosting:**

Viewable via a public link.` https://app.snazzydocs.com/docs/[id]/pdf`, or downloadable with an optional url parameter `?dl=1`.

**Comment by rrasill** [comment]
Hi Roger, do you have any updates on these features? Adding an image to a cover page and a logo to the rest of the document would be very useful for us now. Thanks.

**Comment by snazzyDocs** [comment]
Hey,

No updates yet. I will queue it up though... starting with cover page and water mark.

**Comment by snazzyDocs** [comment]
@rrasill 

A couple questions for ya.

1). What kind of placement options would you expect/find useful for the watermark? Right now (in development), I have top-left, top-right, bottom-left, bottom-right, and center.

2). In terms of watermark sizing...  Are you at all envisioning it being rotated, spanning the full height/width of the pages (like bottom-left to top-right)? (I do not have that functionality built in). 

Here is what the top-right looks like (with an optional filter applied).
<img width="1448" alt="image" src="https://user-images.githubusercontent.com/40471375/228691954-faa1f4a4-20a7-45c4-ad23-0cf4b375b092.png">

An aside -Just a heads up... Applying a watermark makes all links in the PDF non functional... I spend half the day looking for a workaround, but at this time, I cannot make links and watermarks work together.

**Comment by rrasill** [comment]
Hi.


  1.  Only top-left, top-right, bottom-left, and botton-right. This is only to place the logo. So it is important that the watermark starts from page 2, and that it does not overlap the text.
  2.  Sizing: small, no rotation, no spanning.

Thanks!!

**Comment by snazzyDocs** [comment]
Right on... Thanks for the info.

Update to follow.

**Comment by snazzyDocs** [comment]
Alpha #1 awaiting feedback...

**Comment by snazzyDocs** [comment]
Cover page, and watermark live...

**Comment by rrasill** [comment]
I did some tests and it seems that everything is working great. Thanks!

**Comment by snazzyDocs** [comment]
Live and tests good. Closing

**Comment by snazzyDocs** [comment]
Ooops.. reopened.

A couple more tasks in issue yet to be completed.
