### ISSUE TITLE
Editor v2 update closed beta test...

### ISSUE THREAD

**Issue by snazzyDocs** [snazzyDocs/public-snazzyDocs#74]
## Overview
This was created to help guide you through the closed beta testing of this update. 

The update consists largely of architectural data store changes and its adjacent systems. It accommodates a couple long awaited(once impossible) feature requests, and improvements to various existing features. It is the foundation of the next iteration of many great feature requests to come.

## Testing
Closed beta testers will have access to a separate temporary server, completely disconnected from the production app and it's data. Access details have been sent to your team leader.

**Hosting modules (Previews, Viewing published docs, etc.) are currently non functional on this separate testing server.**

## Requirements
While a testing suite exists, essential functionality need to be tested by humans. Each stage contains important editor functionality tests that need completed before progressing to open beta status.

### Stage 1 (General bug hunting)
**_Goals: Find any bugs in basic editor functionality._**

### Stage 2 (Editing & saving)
_**Goals: Insure data integrity and changes made by a user is correctly saved.**_
- [x] Item(chapters/sections/pages) create, remove, edit, delete.
- [x] Item structural changes (moving, name/slug changes, etc.).
- [x] Saving, publishing, partial publishing, restoring (History).

### Stage 3 (Collaboration with 2 or more users)
_**Goals: Insure data integrity and changes made by multiple users are correctly saved. Tests mentioning "coinciding" should be done at the same time(as close as possible anyway. < than 1 second )**_
- [x] Realtime editing.
- [x] Realtime coinciding editing of the same page.
- [x] Realtime coinciding item structural changes (moving, name/slug changes, etc.).

### Stage 4 (Connected Git repositories)
**_Goals: Insure various functionality with connected Git repositories are still working_**
- [x] Repos can be connected.
- [x] Images are properly handled when connected a new repo.
- [x] Repos can be pushed to when publishing.
- [x] Repos can be pulled from.
- [x] Images are properly handled during pushing & pulling.
- [x] HTML markup / Markdown is properly handled on push and pull.

**Comment by snazzyDocs** [comment]
Update pushed to production
